FROM quay.io/jupyter/minimal-notebook:lab-4.2.0

USER root

RUN apt-get update --yes && apt-get install --yes --no-install-recommends \
    jq \
    curl \
    openvpn \
    iputils-ping \
    pciutils

# jovyan
USER ${NB_UID}

RUN pip install jupyter-collaboration

USER root

COPY --chmod=755 ./demiurge-functions.sh /usr/local/bin/

COPY --chmod=755 jupyterlab/page_config.json /etc/jupyter/labconfig/
COPY --chmod=755 jupyterlab/start-singleuser.sh jupyterlab/activity-server.py jupyterlab/demiurge-entrypoint.sh /usr/local/bin/

# Configure container entrypoint
# ENTRYPOINT was ["tini", "-g", "--", "start.sh"]
# CMD was ["start-notebook.py"] (/usr/local/bin/start-notebook.py)

ENTRYPOINT ["tini", "-g", "--", "demiurge-entrypoint.sh"]
CMD [""]
