# https://github.com/jupyter/docker-stacks/blob/main/images/pytorch-notebook/Dockerfile 
FROM quay.io/jupyter/scipy-notebook:lab-4.2.0

USER root

RUN apt-get update --yes && apt-get install --yes --no-install-recommends \
    jq \
    curl \
    openvpn \
    iputils-ping \
    pciutils

# jovyan
USER ${NB_UID}


# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# COPY whl_cache /tmp/whl_cache

## --find-links=./whl_cache \
# RUN pip install --no-cache-dir \
#    /tmp/whl_cache/torch-2.4.1+cu124-cp311-cp311-linux_x86_64.whl \
#    /tmp/whl_cache/torchvision-0.19.1+cu124-cp311-cp311-linux_x86_64.whl \
#    /tmp/whl_cache/torchaudio-2.4.1+cu124-cp311-cp311-linux_x86_64.whl \
#    /tmp/whl_cache/nvidia_cuda_nvrtc_cu12-12.4.99-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_cuda_cupti_cu12-12.4.99-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_cublas_cu12-12.4.2.65-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_cufft_cu12-11.2.0.44-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_curand_cu12-10.3.5.119-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_cuda_runtime_cu12-12.4.99-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_cusolver_cu12-11.6.0.99-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_cusparse_cu12-12.3.0.142-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/nvidia_nvjitlink_cu12-12.4.99-py3-none-manylinux2014_x86_64.whl \
#    /tmp/whl_cache/triton-3.0.0-1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl \
#    /tmp/whl_cache/nvidia_nvtx_cu12-12.4.99-py3-none-manylinux2014_x86_64.whl \
# --index-url https://download.pytorch.org/whl/cu124

RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

RUN pip install --no-cache-dir jupyter-collaboration

USER root

COPY --chmod=755 ./demiurge-functions.sh /usr/local/bin/

COPY --chmod=755 jupyterlab/page_config.json /etc/jupyter/labconfig/
COPY --chmod=755 jupyterlab/start-singleuser.sh jupyterlab/activity-server.py jupyterlab/demiurge-entrypoint.sh /usr/local/bin/

# Configure container entrypoint
# ENTRYPOINT was ["tini", "-g", "--", "start.sh"]
# CMD was ["start-notebook.py"] (/usr/local/bin/start-notebook.py)

ENTRYPOINT ["tini", "-g", "--", "demiurge-entrypoint.sh"]
CMD [""]
