#!/bin/bash
# ============================================================================
# Build the workspace Storybook and serve it at storybook.{domain}
# ============================================================================
# One Storybook covering every package, grouped in the sidebar by the `title`
# each story declares — not one Storybook per package, which fragments the
# component library across a dozen URLs and makes cross-package comparison
# impossible.
#
#   ./build-storybook.sh <env-name>              # build and expose
#   ./build-storybook.sh <env-name> --no-build   # only refresh the vhost
#
# Config lives in .storybook/ at the repository root. The per-package
# .storybook/ directories are still there for `nx run <pkg>:storybook` when
# working on a single package.
#
# Result:
#   https://storybook.{domain}
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ENV_NAME=""
DO_BUILD=true

for arg in "$@"; do
  case "$arg" in
    --no-build) DO_BUILD=false ;;
    -h | --help)
      sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    -*)
      echo "❌ Unknown option: $arg" >&2
      exit 1
      ;;
    *)
      if [ -z "$ENV_NAME" ]; then
        ENV_NAME="$arg"
      else
        echo "❌ Unexpected argument: $arg" >&2
        echo "   Package selection is gone — the Storybook is now a single build." >&2
        exit 1
      fi
      ;;
  esac
done

if [ -z "$ENV_NAME" ]; then
  echo "❌ Usage: $0 <env-name> [--no-build]" >&2
  exit 1
fi

ENV_DIR="/root/.local-dev/${ENV_NAME}"
if [ ! -f "${ENV_DIR}/.env.ganymede" ]; then
  echo "❌ Environment '${ENV_NAME}' not found at ${ENV_DIR}" >&2
  exit 1
fi

DOMAIN=$(grep "^DOMAIN=" "${ENV_DIR}/.env.ganymede" | cut -d= -f2 | tr -d '"')
WORKSPACE=$(grep "^WORKSPACE=" "${ENV_DIR}/.env.ganymede" | cut -d= -f2 | tr -d '"')
WORKSPACE="${WORKSPACE:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"

if [ -z "$DOMAIN" ]; then
  echo "❌ DOMAIN missing from ${ENV_DIR}/.env.ganymede" >&2
  exit 1
fi

OUT="${WORKSPACE}/storybook-static"

echo "📚 Storybook for environment ${ENV_NAME} (${DOMAIN})"
echo "   Workspace: ${WORKSPACE}"
echo ""

cd "$WORKSPACE"

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
if [ "$DO_BUILD" = true ]; then
  echo "🔨 Building the workspace Storybook (a few minutes)..."

  # Peak memory scales with the number of modules, and this build spans every
  # package. Keep the cap comfortably below the machine's RAM: setting it at or
  # above total memory lets the heap grow until the kernel OOM-killer steps in,
  # which shows up as a bare "Killed" rather than a heap error.
  TOTAL_MB=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo 2>/dev/null || echo 8192)
  DEFAULT_HEAP=$((TOTAL_MB * 70 / 100))
  HEAP="${STORYBOOK_NODE_HEAP_MB:-$DEFAULT_HEAP}"
  echo "   Node heap cap: ${HEAP} MB of ${TOTAL_MB} MB total"

  if NODE_OPTIONS="--max-old-space-size=${HEAP} ${NODE_OPTIONS:-}" \
    npx storybook build -c .storybook -o storybook-static >/tmp/storybook-build.log 2>&1; then
    echo "   ✅ built"
  else
    echo "   ❌ build failed — see /tmp/storybook-build.log"
    tail -15 /tmp/storybook-build.log | sed 's/^/      /'
    if grep -q "Killed" /tmp/storybook-build.log; then
      echo ""
      echo "   'Killed' means the kernel OOM-killer, not a Node heap limit."
      echo "   Give the VM more memory:  limactl stop holistix &&"
      echo "                             limactl edit holistix --memory 10 &&"
      echo "                             limactl start holistix"
    fi
    exit 1
  fi
fi

if [ ! -f "${OUT}/index.html" ]; then
  echo "❌ No build at ${OUT} — drop --no-build to produce one" >&2
  exit 1
fi

STORY_COUNT=$(jq -r '.entries | length' "${OUT}/index.json" 2>/dev/null || echo "?")
echo "   ${STORY_COUNT} stories indexed"

# ---------------------------------------------------------------------------
# Nginx vhost
# ---------------------------------------------------------------------------
CONF="/etc/nginx/sites-available/storybook-${ENV_NAME}"
LOGS_DIR="${ENV_DIR}/logs"
sudo mkdir -p "$LOGS_DIR"

sudo tee "$CONF" >/dev/null <<CONFEOF
# Generated by scripts/local-dev/build-storybook.sh for '${ENV_NAME}'
# Do not edit by hand — re-run the script instead.

server {
    listen 443 ssl;
    server_name storybook.${DOMAIN};

    ssl_certificate ${ENV_DIR}/ssl-cert.pem;
    ssl_certificate_key ${ENV_DIR}/ssl-key.pem;

    root ${OUT};
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Storybook fingerprints its assets, so they can be cached.
    location ~* \.(js|css|woff2?|ttf|svg|png|jpg)\$ {
        expires 1h;
        add_header Cache-Control public;
    }

    # index.json is the story index and changes on every build.
    location = /index.json {
        add_header Cache-Control "no-store";
    }

    access_log ${LOGS_DIR}/storybook-access.log;
    error_log ${LOGS_DIR}/storybook-error.log;
}
CONFEOF

sudo ln -sf "$CONF" "/etc/nginx/sites-enabled/storybook-${ENV_NAME}"

echo ""
echo "🔍 Validating Nginx configuration..."
if ! sudo nginx -t 2>&1 | sed 's/^/   /'; then
  echo "❌ Nginx rejected the configuration; the vhost was not enabled." >&2
  sudo rm -f "/etc/nginx/sites-enabled/storybook-${ENV_NAME}"
  exit 1
fi

sudo nginx -s reload 2>/dev/null || sudo service nginx reload

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Storybook exposed — https://storybook.${DOMAIN}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   ${STORY_COUNT} stories from every package, grouped in one sidebar."
echo "   The wildcard certificate and DNS already cover this host."
echo ""
