#!/bin/bash
# Master setup script - runs all one-time setup scripts
# Run this once when setting up local development for the first time

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Local Development - One-Time Setup                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "This will install:"
echo "  - Node.js 24.x"
echo "  - PostgreSQL server"
echo "  - Nginx web server"
echo "  - mkcert (SSL certificates)"
echo "  - PowerDNS (DNS server)"
echo "  - Observability stack (OTLP Collector, Loki, Tempo, Grafana)"
echo "  - Docker images (gateway)"
echo "  - Other dependencies"
echo ""
read -p "Continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
  echo "Cancelled."
  exit 0
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 1/6: Installing Node.js..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
"${SCRIPT_DIR}/install-node.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 2/6: Installing system dependencies..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
"${SCRIPT_DIR}/install-system-deps.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 3/6: Installing mkcert..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
"${SCRIPT_DIR}/install-mkcert.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 4/6: Setting up PostgreSQL..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
"${SCRIPT_DIR}/setup-postgres.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 5/6: Setting up PowerDNS..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
"${SCRIPT_DIR}/setup-powerdns.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 6/7: Setting up Observability Infrastructure..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
"${SCRIPT_DIR}/setup-observability.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 7/7: Building Docker images..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
"${SCRIPT_DIR}/build-images.sh"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ✅ One-Time Setup Complete!                                 ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 IMPORTANT: Host OS Setup Required"
echo ""
echo "1. 🔐 Install mkcert root CA on your host OS (Windows/macOS/Linux):"
echo ""
CA_ROOT=$(mkcert -CAROOT)
echo "   Copy this file to your host OS: ${CA_ROOT}/rootCA.pem"
echo ""
echo "   Quick copy to workspace:"
echo "   $ cp ${CA_ROOT}/rootCA.pem /root/workspace/monorepo/rootCA.pem"
echo ""
echo "   Then on your host OS:"
echo "   - Windows: Right-click rootCA.pem → Install Certificate"
echo "   - macOS: Double-click → Add to System → Always Trust"
echo "   - Linux: certutil -d sql:\$HOME/.pki/nssdb -A -t C,, -n mkcert-dev -i rootCA.pem"
echo ""
echo "   See doc/LOCAL_DEVELOPMENT.md for detailed instructions."
echo ""
echo "2. 🌐 Configure DNS delegation on your host OS (ONE-TIME SETUP)"
echo ""
echo "   PowerDNS is running on port 53 in this container."
echo "   Configure your host OS to use this container for *.domain.local DNS:"
echo ""
echo "   Windows:"
echo "     Network Adapter → Properties → IPv4 → DNS Server: <dev-container-ip>"
echo ""
echo "   macOS:"
echo "     sudo mkdir -p /etc/resolver"
echo "     echo 'nameserver <dev-container-ip>' | sudo tee /etc/resolver/domain"
echo ""
echo "   Linux:"
echo "     Edit /etc/systemd/resolved.conf:"
echo "     [Resolve]"
echo "     DNS=<dev-container-ip>"
echo "     Domains=~domain"
echo ""
echo "   Get dev container IP: hostname -I"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Next: Create your first environment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   ./create-env.sh dev-001 domain.local"
echo ""
echo "   Or with custom domain:"
echo "   ./create-env.sh dev-001 demiurge.local"
echo ""

